// Generated by CoffeeScript 1.9.3
(function() {
  var Converter;

  Converter = (function() {
    function Converter() {}

    Converter.prototype.convert = function(arabic) {
      var i, numeral, ref;
      if (arabic < 4) {
        numeral = '';
        for (i = 1, ref = arabic; 1 <= ref ? i <= ref : i >= ref; 1 <= ref ? i++ : i--) {
          numeral += 'I';
        }
        return numeral;
      } else if (arabic === 4) {
        return 'IV';
      } else {
        return 'V';
      }
    };

    return Converter;

  })();

  describe('Converter', function() {
    var converter;
    converter = {};
    beforeEach(function() {
      return converter = new Converter();
    });
    it('returns "I" when given 1', function() {
      return expect(converter.convert(1)).toEqual('I');
    });
    it('returns "II" when given 2', function() {
      return expect(converter.convert(2)).toEqual('II');
    });
    it('returns "III" when given 3', function() {
      return expect(converter.convert(3)).toEqual('III');
    });
    it('returns "IV" when given 4', function() {
      return expect(converter.convert(4)).toEqual('IV');
    });
    return it('returns "V" when given 5', function() {
      return expect(converter.convert(5)).toEqual('V');
    });
  });

}).call(this);
